# -*- coding: utf-8 -*-
"""Build zh translation dictionary. Core categories translated; the rest
fall back to English automatically via the game's Or() lookup."""
import json, io

zh = {}

# ============ ui ============
zh['ui'] = {
    'play': '开始',
    'settings': '设置',
    'multiplayer': '多人游戏',
    'singleplayer': '单人游戏',
    'nickname': '昵称',
    'roomCode': '房间码',
    'join': '加入',
    'randomJoin': '随机加入',
    'close': '关闭',
    'ok': '确定',
    'save': '保存',
    'load': '读取',
    'reset': '重置',
    'cancel': '取消',
    'confirm': '确认',
    'back': '返回',
    'owned': '已拥有',
    'locked': '未解锁',
    'maxed': '已满级',
    'buyMax': '最大',
    'level': '等级',
    'cost': '费用',
    'playerName': '玩家名',
    'general': '常规',
    'multiplayerMenu': '多人游戏',
    'audioSettings': '音频',
    'videoSettings': '视频',
    'fpsLimit': 'FPS 上限',
    'unlimited': '无限制（垂直同步）',
    'fps60': '60 FPS',
    'fps30': '30 FPS',
    'chest': '宝箱',
    'exportSave': '导出存档',
    'importSave': '导入存档',
    'exitToTitle': '返回标题',
    'startAdventure': '开始冒险',
    'createRoom': '创建房间',
    'yourName': '你的名字',
    'solo': '单人',
    'soloDesc': '按自己的节奏舒适游玩。<br>进度自动保存。',
    'multiDesc': '随机房间资源加成 x1.25！<br>私人房间需 2+ 玩家才有加成。',
    'upgrade': '升级',
    'auto': '自动',
    'companions': '伙伴',
    'on': '开',
    'off': '关',
    'music': '音乐',
    'sfx': '音效',
    'maxSuffix': '最大',
    'speedSuffix': '速度',
    'valueSuffix': '价值',
    'radiusSuffix': '半径',
    'seedsSuffix': '种子',
    'permanentTag': '永久',
    'enterCastle': '进入城堡？',
    'feedbackDiscord': 'Discord',
    'wishlistSteam': '加入 STEAM 愿望单',
    'oneRebirth': '1 次转生',
    'evolution': '进化',
    'evolution3': '进化 3',
    'evolution4': '进化 4',
    'nest2': '巢穴等级 2',
    'nest3': '巢穴等级 3',
    'disableChat': '聊天',
    'disableCustomCursor': '自定义光标',
    'floatTextNotifications': '浮动文字',
}

# ============ messages ============
zh['messages'] = {
    'castCancelled': '抛竿取消！',
    'fishingStart': '开始钓鱼！',
    'fishingCancelled': '钓鱼取消！',
    'caught': '已捕获',
    'alreadyOwned': '已拥有',
    'notEnough': '数量不足',
    'purchased': '已购买！',
    'levelUp': '升级！',
    'fishingLevelUp': '钓鱼等级提升！',
    'soldFish': '已出售',
    'junkRemovalCompensation': '旧钓鱼物品：+{amount} 莫奈塔',
    'rebirth': '转生',
    'rebirthDesc': '重置你的爆米花',
    'earnPer': '每……获得 1 根金色羽毛',
    'playtimeBonus': '游戏时长奖励',
    'moreFeathersUpgrade': '更多羽毛升级',
    'needPopcorn': '',
    'unlocked': '已解锁！',
    'sparrowLevelUp': '麻雀等级提升！',
    'fishCaughtUI': '捕获到鱼！',
    'notEnoughFish': '鱼不够！',
    'fishingXP': '钓鱼经验',
    'nextStageLocked': '下一阶段未解锁！',
    'needRebirth': '需要 1 次转生',
    'needEvolution': '需要进化',
    'needEvolution3': '需要进化 3',
    'needEvolution4': '需要进化 4',
    'needNest2': '需要巢穴等级 2',
    'needNest3': '需要巢穴等级 3',
    'doubleCatch': '双倍捕获！',
    'fedMonster': '已喂食怪物：',
    'notEnoughMoney': '金币不足',
    'wholesale': '批发奖励！',
    'criticalCast': '暴击抛竿！',
    'shinyCatchUI': '闪光捕获！',
    'doubleCatchUI': '双倍捕获！',
    'newRecordUI': '新纪录！',
}

# ============ settings_menu ============
zh['settings_menu'] = {
    'title': '设置',
    'music': '音乐',
    'sfx': '音效',
    'controls': '操作',
    'wasd': 'WASD/方向键',
    'cursorFollow': '光标跟随',
    'clickToWalk': '点击移动',
    'changeMode': 'C - 切换模式',
    'chat': 'T - 聊天',
    'fishInventory': 'F - 鱼背包',
    'profile': 'P - 资料',
    'settings': 'ESC - 设置',
    'language': '语言',
    'game': '游戏',
}

# ============ tabs ============
zh['tabs'] = {
    'shop': '商店',
    'popcorn': '爆米花',
    'prestige': '转生',
    'seeds': '种子',
    'twigs': '树枝',
    'mine': '矿洞',
    'auto': '自动',
}

# ============ rarities ============
zh['rarities'] = {
    'all': '全部',
    'common': '普通',
    'uncommon': '优秀',
    'rare': '稀有',
    'epic': '史诗',
    'legendary': '传说',
}

# ============ fishTypes ============
zh['fishTypes'] = {
    'coastal': '近海',
    'reef': '珊瑚礁',
    'freshwater': '淡水',
    'river': '河流',
    'ocean': '海洋',
    'creature': '生物',
    'exotic_reef': '异域珊瑚礁',
    'spirit': '灵魂',
    'cosmic': '宇宙',
    'mechanical': '机械',
    'crab': '螃蟹',
    'abyssal': '深渊',
    'expedition': '探险',
}

# ============ currencies ============
zh['currencies'] = {
    'popcorn': '爆米花',
    'goldenPopcorn': '金色爆米花',
    'goldenFeathers': '金色羽毛',
    'sunflowerSeeds': '种子',
    'monetariaMoneta': '莫奈塔',
    'fishCaught': '捕获的鱼',
    'dungeonKey': '地牢钥匙',
    'twigs': '树枝',
    'bruteOre': '原矿',
    'oreBars': '矿锭',
    'deepCores': '深层核心',
}

# ============ currencyTooltips ============
zh['currencyTooltips'] = {
    'popcorn': '吃掉地上捡到的爆米花。',
    'goldenPopcorn': '来自特殊爆米花掉落的稀有沙漠货币。',
    'goldenFeathers': '通过转生或完成特殊目标获得。',
    'sunflowerSeeds': '由向日葵田里的向日葵机生产。',
    'monetariaMoneta': '通过卖鱼获得。',
    'fishCaught': '在池塘（桥地图）钓鱼获得。（里程碑 - 不消耗）',
    'dungeonKey': '由探险第 2 层 Boss 掉落。',
    'bruteOre': '在矿洞地牢的矿脉中开采。',
    'oreBars': '由原矿精炼，用于后续矿洞进度。',
    'deepCores': '通过坍塌矿洞获得，用于宝藏室进度。',
}

# ============ chestUI ============
zh['chestUI'] = {
    'windowTitle': '开宝箱',
    'helpAriaLabel': '开宝箱帮助',
    'helpTitle': '宝箱指南',
    'helpLineRewards': '打开宝箱可获得奖励和装备。',
    'helpLineAutoDiscard': '自动丢弃绝不会丢弃灵魂光环或药水。',
    'skillPointsLabel': '技能点',
    'skillPointsDescription': '用于鹦鹉技能。',
    'spiritAuraLabel': '灵魂光环',
    'spiritAuraDescription': '用于装备升级。',
    'expeditionChestTitle': '材料宝箱',
    'artifactChestTitle': '神器宝箱',
    'selectorExpedition': '材料宝箱',
    'selectorMaterialUncommon': '优秀材料',
    'selectorMaterialRare': '稀有材料',
    'selectorMaterialEpic': '史诗材料',
    'selectorMaterialLegendary': '传说材料',
    'selectorArtifact': '神器宝箱',
    'selectorEquipCommon': '普通装备',
    'selectorEquipUncommon': '优秀装备',
    'selectorEquipRare': '稀有装备',
    'selectorEquipEpic': '史诗装备',
    'selectorEquipLegendary': '传说装备',
    'batchSize': '批量大小',
    'autoDiscard': '自动丢弃',
    'discardRarity': '丢弃 {rarity}',
    'discardDupes': '丢弃重复',
    'dupes': '重复',
    'openOne': '打开 1 个',
    'openX': '打开 x{count}',
    'openUntilFull': '打开至满',
    'rewardTitle': '奖励',
    'openNext': '继续打开 x{count}',
    'done': '完成',
    'inventoryFullShort': '背包已满',
    'inventoryFull': '背包已满',
    'rewardSuffix': '奖励',
    'itemsOwnedSummary': '已拥有物品概览',
    'noRewards': '没有奖励。',
    'chestsCounter': '宝箱',
}

# ============ questMerchant ============
zh['questMerchant'] = {
    'title': '任务商人',
    'objectivesTitle': '目标',
    'objectivesSubtitle': '随时追踪任务和鱼类合同。',
    'objectivesHelpTitle': '目标如何运作',
    'objectivesHelpQuests': '任务追踪探险目标和永久加成。',
    'objectivesHelpContracts': '鱼市场解锁后，可随时查看和管理鱼类合同。',
    'objectivesTabs': {'quests': '任务', 'contracts': '鱼类合同'},
    'subtitle': '每日合同每 24 小时轮换。主线任务为永久。',
    'helpTitle': '任务如何运作',
    'helpDaily': '每日：每位玩家每 24 小时获得 3 个随机任务。',
    'helpDailyRewards': '每日奖励为永久，并与后续每日完成叠加。',
    'helpMain': '主线任务为永久，可随时完成。',
    'helpRewards': '所有奖励均为百分比加成。',
    'pin': '固定',
    'pinned': '已固定',
    'pinQuest': '固定任务',
    'unpinQuest': '取消固定',
    'emptyActive': '没有进行中的合同。',
    'emptyMain': '未配置主线任务。',
    'emptyBuffs': '尚无任务加成生效。',
    'mainQuests': '主线任务',
    'dailyQuests': '每日任务',
    'bonusNote': '每日任务加成为永久，并与新的每日完成叠加。主线任务加成为永久。',
    'tabs': {'active': '进行中', 'index': '索引', 'bonuses': '加成'},
    'summary': {'completed': '已完成', 'active': '进行中', 'buffs': '加成', 'overall': '总计', 'activeStats': '当前属性'},
    'states': {'completed': '已完成', 'active': '进行中', 'open': '可领取'},
    'questTypes': {'main': '主线任务', 'daily': '每日任务'},
    'families': {'floor_kill': '楼层狩猎', 'boss_clear': 'Boss 狩猎', 'enemy_hunt': '敌人狩猎'},
    'rewards': {
        'expedition_chest_chance_flat': {'reward': '{amount} 掉落几率', 'bonus': '掉落几率 {amount}'},
        'seed_gain_mult': {'reward': '{amount} 种子', 'bonus': '种子 {amount}'},
        'popcorn_gain_mult': {'reward': '{amount} 爆米花', 'bonus': '爆米花 {amount}'},
        'twig_gain_mult': {'reward': '{amount} 树枝', 'bonus': '树枝 {amount}'},
        'feather_gain_mult': {'reward': '{amount} 羽毛', 'bonus': '羽毛 {amount}'},
        'expedition_damage_mult': {'reward': '{amount} 探险伤害', 'bonus': '探险伤害 {amount}'},
        'expedition_hp_mult': {'reward': '{amount} 探险生命', 'bonus': '探险生命 {amount}'},
        'expedition_skill_point_mult': {'reward': '{amount} 探险点数', 'bonus': '探险点数 {amount}'},
        'expedition_chest_reward_mult': {'reward': '{amount} 掉落价值', 'bonus': '掉落价值 {amount}'},
        'pickup_radius_mult': {'reward': '{amount} 拾取半径', 'bonus': '拾取半径 {amount}'},
    },
    'quests': {
        'daily_floor1_clearance': {'title': '花园清理', 'description': '在探险第 1 层击败 35 个敌人。'},
        'daily_floor2_predator_control': {'title': '沼泽捕食者控制', 'description': '在探险第 2 层击败 25 个敌人。'},
        'daily_floor3_recon': {'title': '沙丘侦察扫荡', 'description': '在探险第 3 层击败 20 个敌人。'},
        'daily_floor4_tidebreak_patrol': {'title': '破潮巡逻', 'description': '在探险第 4 层击败 18 个敌人。'},
        'daily_floor1_boss': {'title': '第 1 层 Boss 检查点', 'description': '击败第 1 层 Boss 一次。'},
        'daily_floor2_boss': {'title': '第 2 层 Boss 检查点', 'description': '击败第 2 层 Boss 一次。'},
        'daily_floor3_boss': {'title': '第 3 层 Boss 检查点', 'description': '击败第 3 层 Boss 一次。'},
        'daily_floor4_boss': {'title': '第 4 层 Boss 检查点', 'description': '击败第 4 层 Boss 一次。'},
        'daily_hunt_harpy': {'title': '鹰身女妖清除', 'description': '击败 8 只鹰身女妖。'},
        'daily_hunt_witch': {'title': '女巫狩猎', 'description': '击败 3 个女巫。'},
        'daily_hunt_cobra': {'title': '巨蛇扫荡', 'description': '击败 12 条眼镜蛇。'},
        'daily_hunt_whipe': {'title': '鞭线突破', 'description': '击败 10 个鱼人鞭击者。'},
        'daily_hunt_inkbender': {'title': '墨迹清理任务', 'description': '击败 8 个鱼人墨术师。'},
        'main_defeat_anubis': {'title': '击败阿努比斯', 'description': '击败阿努比斯一次。奖励：探险点数获取 x2。'},
        'main_floor3_war_of_attrition': {'title': '消耗战', 'description': '在探险第 3 层击败 1200 个敌人。奖励：探险伤害 x1.2。'},
        'main_floor4_stormfront_breaker': {'title': '风暴前线突破者', 'description': '在探险第 4 层击败 1500 个敌人。奖励：探险生命 x1.3。'},
        'main_floor4_boss_gauntlet': {'title': 'Boss 挑战：第 4 层', 'description': '击败第 4 层 Boss 5 次。奖励：探险点数获取 x3。'},
        'main_floor4_whipline_collapse': {'title': '鞭线崩溃', 'description': '击败 180 个鱼人鞭击者。奖励：掉落价值 x1.25。'},
        'main_floor4_inkbender_blackout': {'title': '墨术师断电', 'description': '击败 140 个鱼人墨术师。奖励：探险点数获取 x1.25。'},
        'main_floor4_tidebreak_pressure': {'title': '破潮压力', 'description': '在探险第 4 层击败 2200 个敌人。奖励：探险点数获取 x1.3。'},
        'main_floor4_brutal_overthrow': {'title': '残暴推翻', 'description': '击败 5 个鱼人蛮兵。奖励：探险点数获取 x1.4。'},
        'main_floor5_horror_encore': {'title': '恐怖加演', 'description': '击败第 5 层 Boss 3 次。奖励：探险点数获取 x2。'},
        'main_floor6_frostline_siege': {'title': '霜线围攻', 'description': '在探险第 6 层击败 2500 个敌人。奖励：探险伤害 x1.35。'},
        'main_floor6_frozen_apex': {'title': '冰封顶点', 'description': '击败第 6 层 Boss 10 次。奖励：探险点数获取 x2.5。'},
        'main_floor6_winter_breaker': {'title': '寒冬突破者', 'description': '在探险第 6 层击败 5000 个敌人。奖励：探险生命 x1.5。'},
    },
}

# ============ offlineRewards ============
zh['offlineRewards'] = {
    'title': '离线谷物',
    'helpAriaLabel': '离线谷物帮助',
    'helpTitle': '离线谷物',
    'helpLineRewards': '小熊猫守护着这些谷物。',
    'helpLineCap': '你离线期间，伙伴们会继续工作 {time}。',
    'awayForMinutes': '离开 {minutes} 分钟',
    'claimButton': '离线谷物 - 领取',
    'claimTooltip': '离线奖励已就绪。离开 {minutes} 分钟。点击领取。',
    'welcomeBackTitle': '欢迎回来！',
    'welcomeBackAway': '你离开了 {time}。',
    'welcomeBackCollect': '领取',
}

# ============ profile ============
zh['profile'] = {
    'title': '玩家资料',
    'openButton': '资料',
    'tabs': {'overview': '概览', 'bonuses': '加成', 'achievements': '成就'},
    'sections': {'resources': '资源', 'multipliers': '倍率', 'fishing': '钓鱼'},
    'stats': {
        'playTime': '游戏时长', 'popcorn': '累计爆米花', 'sunflowerSeeds': '累计种子',
        'goldenFeathers': '累计羽毛', 'twigs': '累计树枝', 'goldenPopcorn': '累计金色爆米花',
        'rebirths': '转生次数', 'fishCaught': '捕获的鱼', 'expeditionFloor': '最高层数',
        'popcornMultiplier': '爆米花倍率', 'rebirbMultiplier': '转生倍率', 'featherMultiplier': '羽毛倍率',
        'seedMultiplier': '种子倍率', 'twigMultiplier': '树枝倍率', 'expeditionPointMultiplier': '探险点数',
        'goldenPopcornMultiplier': '金色爆米花', 'fishingLuck': '钓鱼幸运', 'shinyChanceMultiplier': '闪光几率',
        'fishingSpeed': '捕获冷却', 'reelSpeed': '收线时间', 'fishingXpMultiplier': '钓鱼经验',
        'fishSellMultiplier': '鱼价值',
    },
}

# ============ achievements ============
zh['achievements'] = {
    'toastLabel': '成就已解锁',
    'unlockedCount': '已解锁 {unlocked}/{total}',
    'statusSteamOnly': '仅限 STEAM',
    'statusUnlocked': '已解锁',
    'statusLocked': '未解锁',
    'requiresSteam': '需要 Steam 版本',
    'lockedDescription': '在 Steam 版中解锁此成就。',
    'unlockedRecently': '最近解锁',
    'unlockedAt': '解锁于 {date}',
    'platformSteam': 'STEAM',
    'platformWeb': '网页',
    'items': {
        'first_popcorn': {'name': '第一颗', 'description': '收集 1 颗爆米花。'},
        'popcorn_10k': {'name': '零食储备', 'description': '收集 10,000 颗爆米花。'},
        'popcorn_10m': {'name': '爆米花风暴', 'description': '收集 10,000,000 颗爆米花。'},
        'popcorn_10b': {'name': '无限影院', 'description': '收集 10,000,000,000 颗爆米花。'},
        'first_rebirb': {'name': '首次转生', 'description': '转生一次。'},
        'first_fish': {'name': '首次捕获', 'description': '捕获 1 条鱼。'},
        'nest_level_1': {'name': '筑巢者', 'description': '将巢穴升到 1 级。'},
        'first_expedition_kill': {'name': '实战检验', 'description': '击败 1 个探险敌人。'},
        'evolution_1': {'name': '进化 I', 'description': '达到进化 1。'},
        'evolution_2': {'name': '进化 II', 'description': '达到进化 2。'},
        'evolution_3': {'name': '进化 III', 'description': '达到进化 3。'},
        'evolution_4': {'name': '进化 IV', 'description': '达到进化 4。'},
        'evolution_5': {'name': '进化 V', 'description': '达到进化 5。'},
        'floor_1_boss_clear': {'name': '森林肃清', 'description': '击败第 1 层 Boss。'},
        'floor_2_reached': {'name': '第二层', 'description': '抵达探险第 2 层。'},
        'floor_3_reached': {'name': '第三层', 'description': '抵达探险第 3 层。'},
        'floor_4_reached': {'name': '第四层', 'description': '抵达探险第 4 层。'},
        'floor_5_reached': {'name': '第五层', 'description': '抵达探险第 5 层。'},
        'hat_ash_cap': {'name': '灰烬帽', 'description': '完成鱼类图鉴。'},
        'hat_boss_1_master': {'name': '眼镜蛇', 'description': '击败第 1 层 Boss 10 次。'},
        'hat_boss_2_master': {'name': '女巫', 'description': '击败第 2 层 Boss 10 次。'},
        'hat_boss_3_master': {'name': '阿努比斯', 'description': '击败第 3 层 Boss 10 次。'},
        'hat_boss_4_master': {'name': '图图', 'description': '击败第 4 层 Boss 10 次。'},
        'hat_boss_5_master': {'name': '克苏鲁', 'description': '击败第 5 层 Boss 10 次。'},
        'hat_builder': {'name': '建造者', 'description': '将巢穴等级升到最大。'},
        'hat_bunny': {'name': '兔子', 'description': '3 秒内穿过桥梁。'},
        'hat_captain': {'name': '船长', 'description': '在第 4 层击败图图鲨。'},
        'hat_chef': {'name': '厨师', 'description': '同时拥有 3 个闪光加成。'},
        'hat_cowboy': {'name': '牛仔', 'description': '收集 1,000,000 颗金色爆米花。'},
        'hat_devil': {'name': '恶魔', 'description': '抵达第 9 层。'},
        'hat_holy': {'name': '圣者', 'description': '抵达第 10 层。'},
        'hat_heisenberg': {'name': '海森鸟', 'description': '吃掉一条传说爆米花鱼。'},
        'hat_lucky': {'name': '幸运儿', 'description': '发现所有闪光鱼。'},
        'hat_pirate': {'name': '海盗', 'description': '解锁探险。'},
        'hat_rasta': {'name': '拉斯特', 'description': '游玩 4 小时 20 分钟。'},
        'hat_santa': {'name': '圣诞老人', 'description': '赢得 25 场街机比赛。'},
        'hat_skull': {'name': '骷髅', 'description': '击杀 100,000 个探险怪物。'},
        'hat_spring': {'name': '春天', 'description': '购买向日葵自动贩卖。'},
        'hat_top': {'name': '高顶礼帽', 'description': '拥有 1,000,000,000 颗爆米花。'},
        'hat_pilgrim': {'name': '朝圣者', 'description': '获得 1,000,000,000 颗种子。'},
        'hat_waldo': {'name': '沃尔多', 'description': '在 Steam 发布日游玩。'},
    },
}

# ============ mobile ============
zh['mobile'] = {
    'menu': '菜单',
    'fish': '鱼',
    'sparrow': '麻雀',
    'parrot': '鹦鹉',
    'dave': '戴夫',
    'seagull': '海鸥',
}

# ============ matchmaking ============
zh['matchmaking'] = {
    'title': '游戏房间',
    'panelHint': '用于淘汰赛的树枝巢穴大厅。',
    'bannerTitle': '匹配',
    'boardTitle': '游戏房间',
    'boardHint': '点击或按 M',
    'codeLabel': '代码',
    'randomRoomLabel': '随机',
    'connectingLabel': '连接中',
    'notInLobby': '不在房间中。',
    'activeStatus': '当前房间',
    'leaveMatchmaking': '离开房间',
    'leaveFirst': '请先离开匹配',
    'joiningRandomMessage': '正在加入随机房间...',
    'leftMatchmakingMessage': '已离开房间',
    'switchFromStandardNotice': '加入游戏房间将离开你当前的多人房间。',
    'switchingRoomsMessage': '正在从多人房间切换到游戏房间...',
    'standardRoomNotice': '当前多人房间：',
    'enterValidCode': '请输入有效的房间码',
    'settingsStatusPrefix': '游戏房间',
    'spectateAction': '观战',
    'spectatingMatchmakingMessage': '正在观战比赛',
    'joinedMatchmakingMessage': '已加入匹配队列',
}

# ============ birbout ============
zh['birbout'] = {
    'waitingLabel': '等待中',
    'startingLabel': '开始中',
    'turnLabel': '回合',
    'powerLabel': '力度',
    'resolvingLabel': '结算中',
    'shrinkingLabel': '收缩中',
    'winnerLabel': '获胜者',
    'drawLabel': '平局',
    'drawSubLabel': '本回合没有赢家',
    'aliveLabel': '存活',
    'windLabel': '风力',
    'playersLabel': '玩家',
    'spectatorBadge': '观众',
    'spectatingLabel': '观战中',
    'dragHint': '右键 + 拖动来瞄准并设置力度',
    'needMorePlayers': '还需 {count} 名玩家才能开始',
    'youTag': '你',
    'outTag': '出局',
    'noPlayersYet': '暂无玩家。',
    'arcadeTitle': '街机',
    'playersTitle': '玩家',
    'mainRoomTitle': '主房间',
    'birboutTitle': 'BIRBOUT',
}

# ============ fishingEffects ============
zh['fishingEffects'] = {
    'reel_speed_mult': '收线速度',
    'luck': '幸运',
    'radius': '半径',
    'specific_fish': '目标',
    'type_boost': '类型加成',
    'exclusive_type': '仅捕获',
    'shiny_type_boost': '闪光加成',
    'rod_fish_mult': '鱼竿鱼',
    'fishing_xp_mult': '钓鱼经验',
    'xp_mult': '钓鱼经验',
    'popcorn_mult': '爆米花',
    'seeds_mult': '种子',
    'seed_mult': '种子',
    'feathers_mult': '羽毛',
    'feather_mult': '羽毛',
    'pickup_mult': '半径',
    'golden_popcorn_mult': '金色爆米花',
    'speed_mult': '速度',
    'parrot_skill_point_mult': '技能点',
    'parrot_hp_mult': '鹦鹉生命',
    'parrot_damage_mult': '鹦鹉伤害',
    'parrot_attack_speed_mult': '鹦鹉攻击速度',
    'parrot_move_speed_mult': '鹦鹉移动速度',
    'parrot_life_regen_mult': '鹦鹉回复',
    'default': '效果',
}

# ============ upgrades ============
zh['upgrades'] = {
    'p_value': {'name': '爆米花价值', 'description': '提升爆米花价值'},
    'p_golden_popcorn_value': {'name': '金色爆米花价值', 'description': '提升获得的金色爆米花'},
    'p_speed': {'name': '更快的爆米花', 'description': '缩短生成时间'},
    'p_capacity': {'name': '爆米花上限', 'description': '屏幕上更多爆米花'},
    'p_move_speed': {'name': '翅膀训练', 'description': '移动更快'},
    'pr_popcorn_mult': {'name': '爆米花倍率', 'description': '倍乘所有爆米花价值'},
    'pr_radius_mult': {'name': '磁场', 'description': '提升拾取半径'},
    'pr_respawn_mult': {'name': '重生倍率', 'description': '爆米花重生更快'},
    's_more_popcorn': {'name': '更多爆米花', 'description': '倍乘爆米花获取'},
    's_more_feathers': {'name': '更多羽毛', 'description': '倍乘羽毛获取'},
    's_more_seeds': {'name': '更多种子', 'description': '倍乘种子获取'},
    't_more_popcorn': {'name': '更多爆米花', 'description': '爆米花倍率翻倍'},
    't_more_rebirths': {'name': '更多金色羽毛', 'description': '金色羽毛翻倍'},
    't_more_seeds': {'name': '更多种子', 'description': '种子倍率翻倍'},
    't_autoclicker': {'name': '更快生成', 'description': '树木生成更快'},
    't_forest_capacity': {'name': '树木上限', 'description': '提升树木上限'},
    't_more_twigs': {'name': '更多树枝', 'description': '提升每棵树获得的树枝价值'},
    't_auto_popcorn': {'name': '自动爆米花', 'description': '自动购买爆米花升级'},
    't_auto_prestige': {'name': '自动金色羽毛', 'description': '自动购买金色羽毛升级'},
    't_auto_seeds': {'name': '自动种子', 'description': '自动购买种子升级'},
    'm_ore_cap': {'name': '矿石上限', 'description': '矿洞中更多矿脉和更大重生爆发'},
    'm_ore_respawn': {'name': '矿石重生', 'description': '矿脉恢复更快'},
    'm_ore_value': {'name': '矿石价值', 'description': '提升每个矿脉获得的原矿'},
    'p_auric_silo': {'name': '金色粮仓', 'description': '提升爆米花上限'},
    'pr_golden_popcorn_mult': {'name': '金色爆米花倍率', 'description': '倍乘获得的金色爆米花'},
    'm_more_ores': {'name': '更多矿石', 'description': '倍乘矿脉获得的原矿'},
    'm_speed_ores': {'name': '矿石速度', 'description': '倍乘矿石重生速度'},
}

# ============ rods ============
zh['rods'] = {
    'rod_simple': {'name': '简易', 'description': '只是一根棍子和一根线。'},
    'rod_normal': {'name': '结实', 'description': '更好的抛竿速度。'},
    'rod_reinforced': {'name': '强化', 'description': '更坚固，冷却更快。'},
    'rod_pro': {'name': '专业', 'description': '为认真的钓手打造。'},
    'rod_fiberglass': {'name': '玻璃纤维', 'description': '现代科技，冷却低。'},
    'rod_carbon': {'name': '碳纤维', 'description': '超轻，超快抛竿。'},
    'rod_mechanic': {'name': '蒸汽机械', 'description': '齿轮实现快速抛竿。'},
    'rod_coco': {'name': '椰子', 'description': '热带速度。'},
    'rod_banana': {'name': '香蕉', 'description': '钾元素动力冷却。'},
    'rod_roots': {'name': '自然之根', 'description': '自然能量快速流动。'},
    'rod_pirate': {'name': '海盗钩', 'description': '快速装填。'},
    'rod_skeleton': {'name': '骨制', 'description': '诡异但高效。'},
    'rod_lizard': {'name': '蜥蜴脊骨', 'description': '灵活快速抛竿。'},
    'rod_shark': {'name': '顶级捕食者', 'description': '以速度狩猎。'},
    'rod_green': {'name': '翡翠', 'description': '均衡且快速。'},
    'rod_blue': {'name': '蓝宝石', 'description': '坚固快速的鱼竿。'},
    'rod_infernal': {'name': '地狱', 'description': '瞬间煮沸大海。'},
    'rod_void_v2': {'name': '虚空延伸', 'description': '瞬间冷却。'},
    'rod_rune': {'name': '符文', 'description': '铭刻着古老魔法。'},
    'rod_ancient': {'name': '远古丛林', 'description': '被粗藤缠绕。'},
    'rod_abyssal_v2': {'name': '深渊之底', 'description': '海洋绝对的最深处。'},
    'rod_prism': {'name': '棱镜', 'description': '闪耀着内在光芒。'},
    'rod_divine': {'name': '神圣', 'description': '受到鸟神祝福。'},
}

# ============ baits ============
zh['baits'] = {
    'bait_crab': {'name': '螃蟹饵', 'description': '螃蟹喜欢这种气味。'},
    'bait_spirit': {'name': '灵魂香', 'description': '吸引灵魂。'},
    'bait_mech': {'name': '电池饵', 'description': '激起机械的兴趣。'},
    'bait_cosmic': {'name': '星尘饵', 'description': '散发着宇宙能量。'},
    'bait_abyssal': {'name': '深渊之光', 'description': '在深处闪耀。'},
    'bait_coastal_chum': {'name': '近海鱼饵', 'description': '吸引近海鱼类的咸味鱼饵。'},
    'bait_reef_coral': {'name': '珊瑚屑', 'description': '吸引珊瑚礁鱼类的明亮碎屑。'},
    'bait_freshwater_pellet': {'name': '睡莲颗粒', 'description': '吸引湖鱼的新鲜植物。'},
    'bait_river_grub': {'name': '河流幼虫', 'description': '吸引河鱼的蠕动零食。'},
    'bait_ocean_minnow': {'name': '海洋米诺鱼', 'description': '吸引海鱼的小型诱饵零食。'},
    'bait_creature_morsel': {'name': '生物碎块', 'description': '适合奇特胃口的大饵。'},
    'bait_exotic_reef_prism': {'name': '棱镜薄片', 'description': '吸引异域珊瑚礁鱼类的闪光薄片。'},
    'shiny_bait_coastal': {'name': '闪耀近海鱼饵', 'description': '提升近海鱼类的闪光几率。'},
    'shiny_bait_reef': {'name': '闪耀珊瑚屑', 'description': '提升珊瑚礁鱼类的闪光几率。'},
    'shiny_bait_freshwater': {'name': '闪耀睡莲颗粒', 'description': '提升淡水鱼类的闪光几率。'},
    'shiny_bait_river': {'name': '闪耀河流幼虫', 'description': '提升河鱼的闪光几率。'},
    'shiny_bait_ocean': {'name': '闪耀海洋米诺鱼', 'description': '提升海鱼的闪光几率。'},
    'shiny_bait_creature': {'name': '闪耀生物碎块', 'description': '提升生物鱼的闪光几率。'},
    'shiny_bait_exotic_reef': {'name': '闪耀棱镜薄片', 'description': '提升异域珊瑚礁鱼类的闪光几率。'},
    'shiny_bait_crab': {'name': '闪耀螃蟹饵', 'description': '提升螃蟹鱼的闪光几率。'},
    'shiny_bait_spirit': {'name': '闪耀灵魂香', 'description': '提升灵魂鱼的闪光几率。'},
    'shiny_bait_mechanical': {'name': '闪耀电池饵', 'description': '提升机械鱼的闪光几率。'},
    'shiny_bait_cosmic': {'name': '闪耀星尘饵', 'description': '提升宇宙鱼的闪光几率。'},
    'shiny_bait_abyssal': {'name': '闪耀深渊之光', 'description': '提升深渊鱼的闪光几率。'},
    'shiny_bait_expedition': {'name': '闪耀探险口粮', 'description': '提升探险鱼的闪光几率。'},
    'hook_wood': {'name': '木制鱼钩', 'description': '简单可靠的鱼钩。'},
    'hook_bronze': {'name': '青铜鱼钩', 'description': '闪亮而锋利。'},
    'hook_iron': {'name': '铁制鱼钩', 'description': '为巨物锻造。'},
    'hook_gold': {'name': '黄金鱼钩', 'description': '海洋的财富。'},
    'hook_diamond': {'name': '钻石鱼钩', 'description': '坚不可摧的完美。'},
    'hook_ancient': {'name': '远古鱼钩', 'description': '被时间遗忘。'},
    'hook_cursed': {'name': '诅咒鱼钩', 'description': '掌控你的运气。'},
    'lure_basic': {'name': '基础诱饵', 'description': '帮助寻找鱼竿鱼。'},
    'lure_advanced': {'name': '高级诱饵', 'description': '对鱼竿鱼有强吸引力。'},
    'lure_pro': {'name': '专业诱饵', 'description': '专业级。'},
    'lure_master': {'name': '大师诱饵', 'description': '鱼竿鱼无法抗拒。'},
    'lure_legend': {'name': '传说诱饵', 'description': '终极鱼竿助手。'},
    'bait_meat': {'name': '肉块', 'description': '给大鱼的大饵。'},
    'bait_ball_pink': {'name': '面团球', 'description': '香甜气味吸引多种鱼。'},
    'hook_emerald': {'name': '翡翠鱼钩', 'description': '注入自然之力。'},
    'hook_grey_heavy': {'name': '重型鱼钩', 'description': '下沉更快。'},
    'hook_grey_light': {'name': '轻型鱼钩', 'description': '精巧呈现。'},
    'hook_ice_blue': {'name': '寒冰鱼钩', 'description': '使水变冷。'},
    'hook_silver': {'name': '白银鱼钩', 'description': '纯净明亮。'},
    'hook_stone': {'name': '石制鱼钩', 'description': '古老设计。'},
    'lure_blue': {'name': '蓝色米诺诱饵', 'description': '模仿小型猎物。'},
    'lure_rainbow': {'name': '彩虹诱饵', 'description': '难以抗拒的闪光。'},
    'lure_red': {'name': '红色旋转诱饵', 'description': '鲜艳的动态。'},
    'lure_leaf': {'name': '叶片诱饵', 'description': '自然伪装。'},
    'bait_moss_green': {'name': '绿色苔藓球', 'description': '新鲜水生零食。'},
    'bait_moss_orange': {'name': '橙色苔藓球', 'description': '注入柑橘？'},
    'bait_moss_purple': {'name': '紫色苔藓球', 'description': '神秘香气。'},
    'bait_pouch_red': {'name': '红色饵料袋', 'description': '精选优质鱼饵。'},
}

# ============ maps ============
zh['maps'] = {
    'sacrificeRoom': '献祭室',
    'meadow': '草地',
    'desert': '沙漠',
    'beach': '海滩',
    'sunflowerField': '向日葵田',
    'bridge': '桥',
    'aquarium': '水族馆',
    'castle': '城堡',
    'dungeon': '地牢',
    'nest': '鸟巢',
    'expedition': '探险中心',
    'mineDungeon': '矿洞地牢',
    'mineTreasureRoom': '宝藏室',
}

# ============ currencySources ============
zh['currencySources'] = {
    'popcorn': '在草地各处收集爆米花',
    'goldenPopcorn': '收集爆米花时有稀有几率获得',
    'goldenFeathers': '通过转生获得',
    'sunflowerSeeds': '由向日葵田生产',
    'twigs': '在巢穴森林砍树',
    'wood': '在巢穴森林砍树',
    'monetariaMoneta': '在码头卖鱼',
    'bruteOre': '在矿洞开采矿脉',
    'oreBars': '在精炼厂精炼原矿',
    'deepCores': '通过矿洞坍塌获得',
    'goldOre': '矿洞中稀有的金色矿脉（由坍塌解锁）',
    'strangeKey': '冒险中发现的奇异钥匙',
    'spiritTrash': '探险中由森林之灵掉落',
    'fishHint': '{zone} · 鱼竿等级 {tier}+',
    'fishJunkHint': '钓上 · {zone}',
    'expeditionFishHint': '在探险中钓得',
    'fishZoneCoastal': '近海水域',
    'fishZoneReef': '珊瑚礁水域',
    'fishZoneRiver': '河流水域',
    'fishZoneOcean': '开阔海洋',
    'fishZoneJunk': '任意钓鱼点',
    'fishZoneUnknown': '特殊水域',
}

# ============ monster ============
zh['monster'] = {
    'feed': '喂食',
    'evolve': '进化',
    'progress': '进度',
    'requirements': '要求',
    'sitHere': '坐在这里',
    'press': '按下',
    'active': '激活',
    'evolving': '进化中...',
    'holdToFeed': '长按喂食',
    'nextEvoLocked': '下一进化未解锁',
    'needMoneta': '需要 1,000 莫奈塔',
    'monetaLabel': '莫奈塔',
    'resetUponEvolution': '进化时重置：',
    'resetList': '- 货币与升级（爆米花、金色羽毛、种子）、鱼背包、麻雀倍率。',
    'popcornLabel': '爆米花',
    'feathersLabel': '羽毛',
    'seedsLabel': '种子',
    'permanentlyKept': '永久保留：',
    'keptList': '- 等级、进化次数、地图、鱼货币、鱼竿、钓鱼（50%）',
    'evolutionSummaryStage': '进化 {value}',
    'evolutionSummaryTitle': '进化 {value}：有何变化',
    'evolutionSummaryReset': '重置',
    'evolutionSummaryKeep': '保留',
    'evolutionSummaryResources': '货币：{items}',
    'evolutionSummaryTemporaryUpgrades': '临时场地升级',
    'evolutionSummaryFishingReset': '鱼背包',
    'evolutionSummarySparrowReset': '麻雀等级、经验和鸟群规模',
    'evolutionSummaryResonanceReset': '共鸣经验和主动消耗',
    'evolutionSummaryCoreKept': '等级、地图、转生和进化进度',
    'evolutionSummaryPermanentKept': '永久升级和货币徽章',
    'evolutionSummaryFishingKept': '鱼竿、鱼类图鉴、钓鱼等级和莫奈塔',
    'evolutionSummarySparrowKept': '麻雀经验、鸟群和转生',
    'evolutionSummaryNestKept': '巢穴等级',
    'evolutionSummaryMineKept': '矿洞资源和升级',
    'dialogue': ['...你...', '你和其他人不一样...', '你的羽毛...闪耀着潜力。', '我很虚弱...被困在这个形态里。', '给我...精华。让我成长。', '我将赐予你超越理解的力量。'],
    'evoCinematic1': ['啊...终于。外壳出现了裂缝。', '在漫长的沉睡后，我又能呼吸了...', '你做得很好，小家伙。但这只是开始。', '留在我身边，Birb。一起...我们将重塑现实本身。'],
    'evoCinematic2': ['更多...我需要更多...', '我的形态在变化...地牢几乎无法容纳我。', '你看到了吗，Birb？宇宙浩瀚无垠，而我饥肠辘辘。', '让我们进入存在的下一阶段。'],
    'evoCinematic3': ['出色...这个世界的结构变得清晰。', '我能看到代码...帷幕之后的数字。', '我们还没有结束，小家伙。', '只差一步就能抵达绝对。'],
    'evoCinematic4': ['无限的力量...', '枷锁已消失。我不再被这个领域束缚。', '你服务得很好。现在，见证宇宙的真实本质。', '我们升华...直至无限。'],
    'pruu': 'pruu',
    'evos': {
        'alpha': {'name': '创世记', 'bonus': '解锁钓鱼、更多树木升级和爆米花自动化'},
        'beta': {'name': '出埃及记', 'bonus': '更多升级、资源 x 进化、水族馆'},
        'gamma': {'name': '利未记', 'bonus': '解锁钓鱼自动化。更多树木升级、鸟巢。'},
        'delta': {'name': '民数记', 'bonus': '解锁：巢穴升级、探险、沙漠地图。'},
        'omega': {'name': '申命记', 'bonus': '帷幕开启。新的升级树苏醒。'},
    },
}

# ============ fastTravel ============
zh['fastTravel'] = {
    'noDestinations': '没有可用目的地',
}

# ============ units ============
zh['units'] = {
    'pxPerSec': '像素/秒',
}

# ============ expedition ============
zh['expedition'] = {
    'intro': ['Birb...这个世界之下埋着一些东西。', '我曾经的一部分。散落。被守护。', '这个形态下我无法触及它们。你的鹦鹉可以。', '把它送过传送门。带回被夺走的东西。'],
}

# ============ pombo ============
zh['pombo'] = {
    'stamp': '鸽子<br>邮报™',
}

# ============ tutorial ============
zh['tutorial'] = {
    'welcome': '欢迎！',
    'welcomeDesc': '你是一只鸽子。用 <span style="color: #2a9d8f">WASD</span> 移动。',
    'mobileWelcomeDesc': '你是一只鸽子。在场上 <span style="color: #2a9d8f">触摸并拖动</span> 来移动。',
    'controls': '操作',
    'controlsDesc': '按 <span style="color: #e76f51">C</span> 切换移动方式。',
    'mobileControls': '移动板',
    'mobileControlsDesc': '移动板出现在你触摸的位置，松开后消失。',
    'task': '任务',
    'taskDesc': '吃掉 <span style="color: #e76f51">1 颗爆米花</span>！',
    'yum': '好吃！',
    'yumDesc': '更多零食在等着你。',
    'shop': '商店',
    'shopDesc': '购买升级。',
    'prestige': '转生',
    'prestigeDesc': '重置以获取 <span style="color: #ffd700;">金色羽毛</span>。',
    'prestigeRate': '<span style="color: #e76f51">1,000 爆米花</span> -> <span style="color: #ffd700;">1 根金色羽毛</span>',
    'travel': '旅行',
    'travelDesc': '用方向键寻找新大陆。',
    'ready': '就绪！',
    'readyDesc': '<span style="color: #e76f51">自动收集</span> 已解锁。',
    'next': '下一步 >>',
    'letsGo': '出发！',
    'gotIt': '知道了！',
    'expeditionReplayLabel': '重播探险教程',
    'expeditionParrotTitle': '你的鹦鹉',
    'expeditionParrotDesc': '你的鹦鹉会自动战斗。待在它附近并保住它的命。',
    'expeditionAutoTitle': '手动或自动',
    'expeditionAutoDesc': '快速连点同一敌人可重新发起攻击并更快出招，或开启 <span style="color:#ef4444">自动</span> 让它帮你选择目标。两种都试试，然后点下一步。',
    'expeditionOpenParrotTitle': '打开伙伴',
    'expeditionOpenParrotDesc': '点击 <span style="color:#facc15">伙伴</span> 或按 Tab。',
    'expeditionSelectParrotTitle': '选择鹦鹉',
    'expeditionSelectParrotDesc': '选择 <span style="color:#facc15">鹦鹉</span> 来管理它的升级和装备。',
    'expeditionSkillsTitle': '变强',
    'expeditionSkillsDesc': '敌人会掉落技能点。打开 <span style="color:#facc15">伙伴 [TAB]</span> 并选择一个技能。',
    'expeditionBuildTitle': '选择流派',
    'expeditionBuildDesc': '伤害清怪更快。生命和回复能让鹦鹉活下来。这些升级在多次探险之间保留。',
    'expeditionGearTitle': '神器宝箱',
    'expeditionGearDesc': '精英敌人和 Boss 可能掉落神器宝箱。打开 <span style="color:#c084fc">装备</span> 现在领取一个。',
    'artifactChestOpenTitle': '打开你的神器宝箱',
    'artifactChestOpenDesc': '选择高亮的宝箱按钮。在你至少拥有一个神器宝箱之前它会保持锁定。',
    'artifactChestClaimTitle': '领取一件神器',
    'artifactChestClaimDesc': '打开一个宝箱以揭示其中的神器。每个宝箱只有在奖励成功入账时才会消耗。',
    'artifactChestRewardTitle': '获得神器',
    'artifactChestRewardDesc': '新神器现在在装备背包里，可以装备或在锻造中使用。',
    'expeditionGearAndChestsTitle': '装备与宝箱',
    'expeditionGearAndChestsDesc': '神器塑造你的流派。喙、护甲和光环提升基础属性。从这个界面打开收集到的宝箱。',
    'expeditionReadyTitle': '准备战斗',
    'expeditionReadyDesc': '准备好后关闭鹦鹉菜单。探险会立即继续。',
    'parrotForgeReplayLabel': '重播鹦鹉锻造教程',
    'parrotForgeWelcomeTitle': '鹦鹉锻造',
    'parrotForgeWelcomeDesc': '锻造有四个工作区。用高亮的标签在 <span style="color:#fbbf24">装备</span>、<span style="color:#67e8f9">注入</span>、<span style="color:#c084fc">融合</span> 和 <span style="color:#86efac">自动精炼</span> 之间切换。',
    'parrotForgeEquipmentTitle': '从装备开始',
    'parrotForgeEquipmentDesc': '打开 <span style="color:#fbbf24">装备</span>。此标签可强化鹦鹉装备并处理光环材料。',
    'parrotForgeWorkbenchTitle': '打造鹦鹉',
    'parrotForgeWorkbenchDesc': '在这里升级喙、护甲和光环。下方的材料背包还能把光环向上转换或拆成更低阶。',
    'parrotForgeFirstUpgradeTitle': '选择你的首个升级',
    'parrotForgeFirstUpgradeDesc': '在喙、护甲或光环上花费 <span style="color:#fbbf24">10 普通光环</span>。锻造只有在完成里程碑 I 且负担得起这个首次升级后才会解锁。',
    'parrotForgeInfusionTitle': '打开注入',
    'parrotForgeInfusionOpenDesc': '选择 <span style="color:#67e8f9">注入</span> 来强化一件神器而不改变它的特性。',
    'parrotForgeInfusionWorkbenchTitle': '注入神器',
    'parrotForgeInfusionWorkbenchDesc': '从背包选择一件神器。注入会消耗该神器的技能点，并在确认前预览下一个威力倍率。',
    'parrotForgeFusionTitle': '打开融合',
    'parrotForgeFusionOpenDesc': '选择 <span style="color:#c084fc">融合</span> 把神器合成更高稀有度。',
    'parrotForgeFusionWorkbenchTitle': '三件相同材料',
    'parrotForgeFusionWorkbenchDesc': '从背包选择三件相同稀有度且未装备的神器。融合会消耗它们以及所示的光环，并生成一件下一稀有度的神器。',
    'parrotForgeLockedTitle': '更多锻造模式',
    'parrotForgeLockedDesc': '注入、融合和自动精炼在完成首次灵魂光环献祭里程碑后解锁。它们的标签会显示具体还差多少进度。',
    'parrotForgeInventoryTitle': '锻造背包',
    'parrotForgeInventoryDesc': '筛选器帮你找到类型、稀有度或装备状态。点击物品会把它放入当前配方；在你按下确认按钮之前不会真正生效。',
    'crowMetalworkReplayLabel': '重播金属工艺教程',
    'crowMetalworkTargetTitle': '选择金属工艺',
    'crowMetalworkTargetDesc': '点击一张已解锁的装备卡来选择哪条永久路线接收矿锭：护甲提升生命，喙提升矿洞伤害，光环提升战斗回复。',
    'crowMetalworkRequirementsTitle': '准备装备',
    'crowMetalworkRequirementsDesc': '金属工艺目标需要对应的矿洞升级和传说 +5 装备。锁定卡会显示还缺什么。',
    'crowMetalworkOpenTitle': '打开金属工艺',
    'crowMetalworkOpenDesc': '展开高亮面板来控制所选装备路线。',
    'crowMetalworkRateTitle': '控制矿锭流量',
    'crowMetalworkRateDesc': '选择多少矿锭收入流入这条路线。关闭会保留所有矿锭；25%、50% 和 100% 把当前收入换成永久充能。',
    'crowMetalworkProgressTitle': '填充路线',
    'crowMetalworkProgressDesc': '进度条显示已存矿锭和下一永久等级所需的数量。更换目标不会清掉其他路线已存的进度。',
    'crowMetalworkFinishTitle': '完成强化',
    'crowMetalworkFinishDesc': '充能满后，选择普通强化或黄金淬火。黄金淬火消耗金矿来降低传说灵魂光环成本；确认前不会有任何消耗。',
    'sparrowUnlockedTitle': '新伙伴',
    'sparrowUnlockedDesc': '一只麻雀现在在草地帮忙。它自动收集爆米花，工作时获得经验。',
    'sparrowOpenCompanionsDesc': '打开 <span style="color: #f1c40f">伙伴 [TAB]</span>。',
    'sparrowOpenMenuTitle': '选择麻雀',
    'sparrowOpenMenuDesc': '选择 <span style="color: #f1c40f">麻雀</span> 打开它的伙伴面板。',
    'sparrowProgressTitle': '升级',
    'sparrowProgressDesc': '它收集时会获得经验。每级提升它的速度。',
    'sparrowGrowthTitle': '种子喂食器',
    'sparrowGrowthDesc': '在这里花费种子来获得额外经验。',
    'seagullUnlockedTitle': '海鸥已解锁',
    'seagullOpenCompanionsDesc': '打开 <span style="color: #5dade2">伙伴 [TAB]</span> 认识你的钓鱼伙伴。',
    'seagullOpenMenuTitle': '选择海鸥',
    'seagullOpenMenuDesc': '选择 <span style="color: #5dade2">海鸥</span> 打开它的伙伴面板。',
    'seagullProgressTitle': '等级与转生',
    'seagullProgressDesc': '每次捕获都给海鸥经验。升级以更快捕获，然后转生以获得永久舰队加成。',
    'seagullDoctrineTitle': '选择钓鱼风格',
    'seagullDoctrineDesc': '均衡是中立，猎手偏向更稀有的捕获，训练偏向经验。为 1 号海鸥选一个。',
    'seagullBaitTitle': '每只海鸥的鱼饵',
    'seagullBaitDesc': '打开这个槽位。每只海鸥装备并消耗自己的鱼饵，只影响它自己的捕获。',
    'seagullRouteTitle': '路线与预报',
    'seagullRouteDesc': '名字下方的线显示分配的路线和当前预报。更多路线稍后解锁。',
    'seagullReadyTitle': '自动钓鱼',
    'seagullReadyDesc': '每只海鸥自动钓鱼。绿色计时器显示它下一次捕获的到达时间。',
    'seedFeederUnlockedTitle': '种子喂食器已解锁',
    'seedFeederUnlockedDesc': '打开 <span style="color: #f1c40f">伙伴 [TAB]</span> 进行设置。',
    'seedFeederOpenSparrowTitle': '打开麻雀',
    'seedFeederOpenSparrowDesc': '选择 <span style="color: #f1c40f">麻雀</span>。',
    'seedFeederRateTitle': '选择喂食比例',
    'seedFeederRateDesc': '拖动滑块选择多少种子收入变成麻雀经验。',
    'seedFeederStartTitle': '开始喂食',
    'seedFeederStartDesc': '按 <span style="color: #2ecc71">喂食</span> 开始把种子收入转换成麻雀经验。',
    'seedFeederReadyTitle': '种子变经验',
    'seedFeederReadyDesc': '红色速率是每秒消耗的种子。绿色速率是每秒获得的麻雀经验。',
    'sparrowMilestonesUnlockedTitle': '里程碑已解锁',
    'sparrowMilestonesUnlockedDesc': '进化 2 解锁了永久麻雀里程碑。打开 <span style="color: #a2d149">伙伴 [TAB]</span>。',
    'sparrowMilestonesTitle': '打开里程碑',
    'sparrowMilestonesDesc': '打开高亮的里程碑栏查看它的进度目标。',
    'sparrowMilestonesReadyTitle': '永久加成',
    'sparrowMilestonesReadyDesc': '每个目标完成一次即可在有丝分裂和进化重置后保留加成。',
    'sparrowResonanceUnlockedTitle': '共鸣已解锁',
    'sparrowResonanceUnlockedDesc': '共鸣已就绪。打开 <span style="color: #f1c40f">伙伴 [TAB]</span>。',
    'sparrowResonanceTitle': '麻雀共鸣',
    'sparrowResonanceDesc': '共鸣把麻雀经验转换成爆米花和种子的倍率。',
    'sparrowResonanceDrainTitle': '控制消耗',
    'sparrowResonanceDrainDesc': '用这个按钮开始或停止把当前麻雀经验转换成共鸣之力。',
    'sparrowHowTitle': '麻雀如何运作',
    'sparrowHowDesc': '麻雀通过收集爆米花变强。打开它的菜单查看等级、经验和当前加成。',
    'fishingTitle': '钓鱼已解锁！',
    'fishingDesc': '在桥上按 <span style="color: #22d3ee">空格</span> 抛竿。等待咬钩，然后收竿。',
    'fishingBuffDesc': '捕获的鱼会进入你的鱼背包。',
    'fishingAutoTitle': '鱼增益',
    'fishingAutoDesc': '吃下背包里的鱼来激活增益，比如爆米花、种子、收线速度、半径和钓鱼经验。',
    'fishingBridgeBuffTitle': '鱼增益',
    'fishingBridgeBuffDesc': '捕获的鱼会进入你的鱼背包。吃鱼可激活增益，比如爆米花、种子、收线速度、半径和钓鱼经验。',
    'fishingBridgeHowTitle': '钓鱼如何运作',
    'fishingBridgeHowDesc': '在桥上按 <span style="color: #22d3ee">空格</span> 抛竿。等待鱼咬钩后收竿。',
    'fishingBridgeShinyTitle': '闪光鱼',
    'fishingBridgeShinyDesc': '闪光鱼的增益在 24 小时内强得多，之后作为普通鱼增益继续。出售前右键点击鱼可锁定它们。',
    'fishingBridgeMonetaTitle': '莫奈塔',
    'fishingBridgeMonetaDesc': '卖鱼获得 <span style="color: #94d2bd">莫奈塔币</span>。莫奈塔购买钓鱼升级，之后还能提升鱼的价值。',
    'fishingBridgeRodsTitle': '鱼竿与装备',
    'fishingBridgeRodsDesc': '多钓鱼来解锁更好的鱼竿。在鱼背包里装备鱼饵、鱼钩和诱饵来改善捕获。',
    'fishingBridgeTryTitle': '抛下你的线',
    'fishingBridgeTryDesc': '按 <span style="color: #22d3ee">空格</span> 或点击抛竿。',
    'fishingBridgeInventoryTitle': '你的捕获',
    'fishingBridgeInventoryDesc': '打开鱼类收藏。',
    'fishingBridgeEatTitle': '吃一条鱼',
    'fishingBridgeEatDesc': '选中鱼并点击喂食。',
    'fishingBridgeActiveBuffTitle': '当前增益',
    'fishingBridgeActiveBuffDesc': '打开增益查看当前生效的加成。',
    'fishingBridgeSaleCatchTitle': '要卖的鱼',
    'fishingBridgeSaleCatchDesc': '再钓一条鱼来卖。',
    'fishingBridgeSaleInventoryTitle': '卖掉你的捕获',
    'fishingBridgeSaleInventoryDesc': '打开鱼类收藏。',
    'fishingBridgeSellFishTitle': '赚取莫奈塔',
    'fishingBridgeSellFishDesc': '点击卖 1。鱼会变成莫奈塔。',
    'fishingBridgeTreasureTitle': '钓鱼宝藏',
    'fishingBridgeTreasureDesc': '捕获也可能揭示宝藏。你保留鱼，宝藏立即变成莫奈塔。更好的鱼竿和升级会提升几率。',
    'fishingBridgeSturdyTitle': '你的首个升级',
    'fishingBridgeSturdyDesc': '{rod} 需要 {count} 条 {fishA} 和 {count} 条 {fishB}。稀有度：{rarity} · 类型：{type}。',
    'fishingBridgeEquipmentTitle': '钓鱼装备',
    'fishingBridgeEquipmentDesc': '打开装备。',
    'fishingBridgeBaitTabTitle': '鱼饵',
    'fishingBridgeBaitTabDesc': '打开鱼饵。',
    'fishingBridgeCoastalBaitTitle': '近海鱼饵',
    'fishingBridgeCoastalBaitDesc': '选择近海鱼饵。它只会钓到近海鱼。',
    'fishingBridgeBuyBaitTitle': '购买鱼饵',
    'fishingBridgeBuyBaitDesc': '用莫奈塔买一份近海鱼饵。',
    'fishingBridgeEquipBaitTitle': '装备鱼饵',
    'fishingBridgeEquipBaitDesc': '装备近海鱼饵。',
    'fishingBridgeBaitCatchTitle': '试试鱼饵',
    'fishingBridgeBaitCatchDesc': '抛竿并钓一条近海鱼。',
    'fishingBridgeFishdexOpenTitle': '查看几率',
    'fishingBridgeFishdexOpenDesc': '打开鱼类收藏。',
    'fishingBridgeFishdexTabTitle': '鱼类图鉴',
    'fishingBridgeFishdexTabDesc': '打开鱼类图鉴。',
    'fishingBridgeFishdexChanceTitle': '捕获几率',
    'fishingBridgeFishdexChanceDesc': '最高几率排在最前。鱼饵会排除其他类型；不用鱼饵时，所有可用类型都回到池子里。',
    'fishingBridgeAutoTitle': '自动钓鱼',
    'fishingBridgeAutoDesc': '手动钓满 10 次以解锁自动。',
    'fishingBridgeProgressTitle': '你的下一个目标',
    'fishingBridgeProgressDesc': '收集 {count} 条 {fishA} 和 {count} 条 {fishB} 来购买 {rod}。',
    'aquariumUnlockedTitle': '水族馆已解锁！',
    'aquariumUnlockedDesc': '你达到了钓鱼等级 10。点击下方高亮的箭头前往水族馆。',
    'currentEndTitle': '恭喜！',
    'currentEndDesc': '你已到达当前内容的最末端。游戏持续更新，每周至少 <span style="color: #ffd700">3 次更新</span>，下一次 <span style="color: #ffd700">大更新</span> 很快 <span style="color: #ffd700">到来</span>。<br><br>你可以继续刷资源、推进探险层数、补完你的 <span style="color: #22d3ee">鱼类图鉴</span> 和鱼类精通（如果还没完成），但从此进度会慢下来。<br><br>如果你喜欢这个游戏，请留下带评价的星级评分，这对我们帮助很大。',
}

# ============ fishing ============
zh['fishing'] = {
    'fishdexTab': '鱼类图鉴',
    'fishdexNewBadge': '新',
    'collection': '收藏',
    'rodShop': '鱼竿商店',
    'junk': '垃圾',
    'types': '类型',
    'total': '总计',
    'inventoryEmpty': '还没钓到鱼！',
    'cannotFeedJunk': '怪物不吃垃圾！',
    'owned': '已拥有',
    'value': '价值',
    'active': '生效中',
    'feed': '喂食',
    'sell1': '卖 1',
    'sellAll': '全部卖出',
    'selectFish': '选一条鱼查看详情',
    'selectTackle': '选择钓具查看详情',
    'rodLocked': '这根鱼竿需要进化才能解锁！',
    'equipped': '已装备',
    'rodOwned': '已拥有',
    'tier': '等级',
    'luck': '幸运',
    'speed': '收线速度',
    'rodCooldown': '冷却',
    'treasureChance': '宝藏几率',
    'stats': '属性',
    'equip': '装备',
    'buy': '购买',
    'locked': '未解锁',
    'notOwned': '未拥有',
    'junkDesc': '垃圾可以卖成爆米花。',
    'sellAllJunk': '卖出全部垃圾',
    'oneBuffActive': '[1 个增益] 一次只有一个增益生效',
    'noBuffActive': '[无增益] 喂一条鱼来激活',
    'neededFor': '需要用于',
    'safeToSell': '可安全出售/喂食',
    'neededForEquipment': '需要用于装备',
    'upgrade': '升级',
    'bait': '鱼饵',
    'equipment': '装备',
    'sellSafeAll': '安全出售',
    'sellSafeTooltip': '出售未锁定、非闪光、且不是未拥有鱼竿/钓具/可见升级/已接合同所需的鱼。',
    'noFishToSell': '没有可安全出售的鱼！',
    'equipBoostDesc': '装备鱼饵和诱饵来增强你的钓鱼！',
    'hooks': '鱼钩',
    'consumableBaits': '消耗型鱼饵',
    'permanentLures': '永久诱饵',
    'baitShop': '鱼饵商店',
    'fishCount': '鱼',
    'sell': '出售',
    'bought': '已购买 {n}！',
    'alreadyOwned': '已拥有！',
    'notEnoughPopcorn': '爆米花不足！',
    'notEnoughFeathers': '羽毛不足！',
    'noBaitToEquip': '没有可装备的鱼饵！',
    'baitUnequipped': '已卸下鱼饵',
    'baitEquipped': '已装备 {n}！',
    'lureNotOwned': '未拥有诱饵！',
    'lureUnequipped': '已卸下诱饵',
    'lureEquipped': '已装备 {n}！',
    'soldFish': '卖出 {n} 条鱼，获得 {v}',
    'soldJunk': '卖出 {n}，+{v}',
    'castLine': '抛竿',
    'casting': '抛竿中...',
    'reeling': '收线中...',
    'cooldown': '冷却中...',
    'tackleBox': '钓具箱',
    'inventoryShortcut': '背包 [F]',
    'buffActivated': '增益已激活',
    'alreadyActive': '已经生效！',
    'buffReplaced': '已替换',
    'buffAll': '全部',
    'buffPopcorn': '爆米花',
    'buffFeather': '羽毛',
    'buffSeed': '种子',
    'buffSpeed': '速度',
    'buffPickup': '拾取',
    'buffXP': '经验',
    'buffReel': '收线',
    'hideCaughtNotification': '隐藏捕获弹窗',
    'selectBuffToReplace': '选择要替换的增益',
    'replace': '替换',
    'fishdex': '收藏',
    'fishdexDiscovered': '已发现',
    'fishdexUndiscovered': '???',
    'fishdexCatchChance': '捕获几率',
    'fishdexMinTier': '最低鱼竿等级',
    'personalBest': '个人最佳',
    'fishdexBestRod': '最佳鱼竿',
    'fishdexBestBait': '最佳鱼饵',
    'fishdexProgress': '已发现',
    'fishdexNotCaught': '尚未捕获',
    'fishdexYouHave': '你拥有',
    'fishdexCannotCatch': '无法捕获',
    'fishdexNeedsBetterRod': '需要更好的鱼竿',
    'fishdexFilterAll': '全部',
    'fishdexFilterDiscovered': '已捕获',
    'fishdexFilterUndiscovered': '未捕获',
    'fishdexSearch': '搜索...',
    'fishdexFilterUnmastered': '未捐献',
    'fishdexFilterMissingShiny': '闪光未捕获',
    'fishdexInventoryLabel': '背包',
    'fishdexTotalLabel': '{count} 总计',
    'fishdexSpeciesLabel': '种类',
    'fishdexSafeValueLabel': '安全价值',
    'fishdexSellUnmasteredWarning': '这会卖掉尚未捐献的鱼。如需要，请先捐献一份。',
    'fishdexVariantAll': '全部',
    'fishdexVariantNormal': '普通',
    'fishdexVariantShiny': '闪光',
    'fishdexAllTypes': '类型',
    'fishdexAllLocations': '地点',
    'fishdexRarities': '稀有度',
    'fishdexLocationBridge': '桥',
    'fishdexLocationFloor': '第 {floor} 层',
    'fishdexAllBuffs': '增益',
    'fishdexNoBuff': '无增益',
    'fishdexMarkersTitle': '鱼类图鉴标记',
    'fishdexShinyDiscovered': '已发现闪光。',
    'fishdexShinyInAquarium': '闪光鱼在水族馆中。',
    'shinyExpired': '闪光已过期',
}

# ============ fishMarket ============
zh['fishMarket'] = {
    'parrotVendorTitle': '鱼饵商人',
    'baitMerchantTitle': '鱼饵商人',
    'contractsTitle': '鱼类合同',
    'marketBuffs': '市场增益',
    'parrotContractsMoved': '市场增益现在来自鱼类合同。去找合同店员。',
    'noActiveBuffs': '没有生效的市场增益。',
    'reputation': '声望',
    'rankValue': '等级 {level}',
    'maxRank': '最大',
    'acceptedSlots': '已接槽位',
    'acceptCooldown': '接单冷却：{time}',
    'refresh': '刷新看板',
    'reroll': '重新随机',
    'acceptedContracts': '已接合同',
    'boardOffers': '看板报价',
    'acceptedContract': '已接合同',
    'boardContract': '看板合同',
    'noAcceptedContracts': '没有已接合同。',
    'noContractOffers': '现在没有合同。',
    'accept': '接受',
    'claim': '领取',
    'abandon': '放弃',
    'ready': '就绪',
    'missing': '缺失',
    'lockedFishWarning': '锁定的鱼不计入',
    'shinyFishName': '闪光 {name}',
    'repReward': '+{amount} 声望',
    'forDuration': '持续 {time}',
    'offersRerolled': '合同已重新随机。',
    'noRerolls': '没有重新随机次数。',
    'contractAccepted': '合同已接受。',
    'contractClaimed': '合同已完成。',
    'contractAbandoned': '合同已放弃。',
    'contractExpired': '合同已过期。',
    'contractMissingFish': '缺少合同所需的鱼。',
    'contractSlotsFull': '没有可用合同槽位。',
    'contractAlreadyAccepted': '合同已接受。',
    'contractCooldownMessage': '店员还在冷却账本。',
    'abandonConfirmTitle': '放弃合同？',
    'abandonConfirmBody': '放弃此合同不消耗鱼，但 {time} 内你无法接受新合同。',
    'abandonConfirmWarning': '已接合同的进度将丢失。',
    'abandonConfirmCancel': '保留',
    'abandonConfirmAction': '放弃',
    'shinyBaits': '闪光鱼饵',
    'baitMerchantDesc': '用莫奈塔购买的类型专用鱼饵。每次抛竿消耗一份已装备鱼饵。',
    'baitMerchantHelpShiny': '闪光鱼饵花费莫奈塔，并提升某一种鱼的闪光几率。',
    'baitMerchantHelpEquip': '直接从这个市场摊位购买并装备闪光鱼饵。',
    'shinyBaitEffect': '闪光 {type} x{amount}',
    'shinyBaitCatchBoost': '类型捕获几率 x{amount}',
    'ownedCount': '拥有 {amount}',
    'lockedEvolution': '进化 {level} 前锁定',
    'buyOne': '买 1',
    'buyTen': '买 10',
    'tutorialWelcomeTitle': '鱼市',
    'tutorialWelcomeBody': '这个市场把闪光鱼进度变成更强的钓鱼选项。和企鹅交谈打开各个摊位。',
    'tutorialBaitsTitle': '鱼饵商人',
    'tutorialBaitsBody': '用莫奈塔买闪光鱼饵，然后在这里或从鱼背包装备。每次抛竿消耗一份已装备鱼饵，并提升该鱼类型的闪光几率。',
    'tutorialContractsTitle': '鱼类合同',
    'tutorialContractsBody': '接受合同、交付所需鱼并领取声望。更高等级改善合同看板并解锁更好的奖励。',
    'helpAccept': '从看板接受合同，当所有鱼需求就绪后领取。',
    'helpLocked': '锁定的鱼不计入，也绝不会被消耗。',
    'helpRewards': '合同消耗鱼以换取声望和临时市场增益。',
    'helpSlots': '更高声望解锁更多已接合同槽位。',
    'buffExpeditionDamage': '鹦鹉伤害',
    'buffExpeditionHp': '鹦鹉生命',
    'buffExpeditionLifeRegen': '鹦鹉回复',
    'buffExpeditionMoveSpeed': '鹦鹉移速',
    'buffExpeditionAttackSpeed': '鹦鹉攻速',
    'buffExpeditionSkillPoints': '技能点',
    'buffExpeditionChestRewards': '掉落价值',
    'buffFishingSpeed': '钓鱼速度',
    'buffFishingXp': '钓鱼经验',
    'buffFishingLuck': '钓鱼幸运',
    'buffShinyChance': '闪光几率',
    'vendorParrotLabel': '鱼饵商人',
    'exitAquariumLabel': '水族馆',
    'offerExpired': '报价已过期。',
    'offerAlreadyBought': '已购买。',
    'buffActive': '增益生效中。',
    'shinyBadge': '闪光',
    'pinned': '已固定',
    'pin': '固定',
    'reward': '奖励',
}

# ============ sparrow ============
zh['sparrow'] = {
    'title': '麻雀',
    'level': '等级',
    'xp': '经验',
    'mitosisProgress': '有丝分裂进度',
    'mitosisButton': '有丝分裂',
    'mitosisTooltip': '让你的麻雀翻倍！',
    'autoMitosis': '自动有丝分裂',
    'autoRebirb': '自动转生',
    'autoMitosisUnlock': '解锁自动有丝分裂。',
    'autoRebirbUnlock': '解锁自动转生。',
    'sparrowCount': '麻雀',
    'sparrowSingular': '麻雀',
    'flightSpeed': '飞行速度',
    'resonance': '共鸣',
    'multiplier': '倍率',
    'sacrificedXp': '牺牲能量',
    'startDraining': '开始消耗',
    'stopDraining': '停止消耗',
    'totalValue': '总价值',
    'seedFeederTitle': '种子喂食器',
    'seedFeederTooltip': '用你当前种子收入的选定百分比换取麻雀经验。只花费你拥有的种子。如果种子收入为 0，它会等待。经验获取上限为每秒下一级的 25%。喂食和消耗不能同时进行。',
    'autoFeed': '自动喂食：{percent}%',
    'startAuto': '开始自动',
    'feed': '喂食',
    'feedingRate': '喂食中：{amount} 种子/秒',
    'feedingWaiting': '喂食中：等待种子收入',
    'feedingZero': '喂食中：0 种子/秒',
    'drainingStatus': '消耗经验中...',
    'convertXpToPower': '把经验转换成力量',
    'prestigeInfo': '重置麻雀。<br>倍乘爆米花生成速率与麻雀经验获取。',
    'milestonesTitle': '里程碑',
    'milestonesTooltip': '达成麻雀进度目标以解锁永久加成。',
    'milestones': {
        'steady_feeder': {'label': '喂食 +50%', 'description': '麻雀达到 50 级一次。种子提供 50% 更多经验。'},
        'resonance_flow': {'label': '共鸣 +25%', 'description': '消耗提供 25% 更多共鸣经验。'},
        'mitosis_rhythm': {'label': '有丝分裂 -20%', 'description': '有丝分裂和转生需要的麻雀经验减少 20%。'},
        'full_flock': {'label': '喂食 +25%', 'description': '种子再提供 25% 经验。'},
        'first_rebirb': {'label': '共鸣 +25%', 'description': '消耗再提供 25% 更多共鸣经验。'},
        'loop_engine': {'label': '有丝分裂 -15%', 'description': '有丝分裂和转生需要的麻雀经验再减少 15%。'},
    },
}

# ============ dave ============
zh['dave'] = {
    'title': '戴夫',
    'helpTitle': '沙漠觅食',
    'helpBody': '戴夫通过收集沙漠爆米花获得经验。向日葵种子提升他的经验获取，而转生本能赋予旅行速度、觅食范围和金色加成。',
    'sweepMeter': '戴夫经验',
    'levelBoostNote': '戴夫每级 +1% 获得的金色爆米花，上限 +1,000%。',
    'stateLabel': '状态',
    'desertStatus': '沙漠状态',
    'totalPopcorn': '总爆米花',
    'visibleGolden': '金色爆米花',
    'sandstorm': '沙尘暴',
    'chargeRate': '经验获取',
    'sweepSize': '觅食范围',
    'scouting': '侦察中',
    'diving': '俯冲中',
    'sweeping': '觅食中',
    'resting': '休息中',
    'ready': '就绪',
    'active': '生效',
    'coolingDown': '冷却中',
    'keenEyes': '节奏',
    'keenEyesDesc': '更快捡取。',
    'broadWings': '范围',
    'broadWingsDesc': '每次扫掠更多拾取。',
    'gildedInstinct': '金色加成',
    'gildedInstinctDesc': '戴夫获得更多金色爆米花。',
    'stormSense': '旅行速度',
    'stormSenseDesc': '在觅食点之间移动更快。',
    'lifetimeStats': '生涯统计',
    'lifetimeSweeps': '扫掠次数',
    'lifetimePopcorn': '收集的爆米花',
    'lifetimeGolden': '金色拾取',
    'currentBonus': '当前',
    'seedSnacks': '种子零食',
    'seedSnacksDesc': '花费向日葵种子来提升戴夫的经验获取。',
    'scanRateShort': '经验获取',
    'pickupsShort': '拾取',
    'goldenFocusShort': '金色',
    'stormBonusShort': '速度',
    'milestonesTitle': '里程碑',
    'rebirbTitle': '转生',
    'rebirbDesc': '达到 50 级，然后在转生时选择一个永久本能。',
    'rebirbBonus': '金色加成',
    'rebirbNext': '下一个',
    'rebirbProgress': '需要 {level} 级。',
    'rebirbAction': '戴夫转生',
    'rebirbLocked': '戴夫转生随戴夫解锁。',
    'rebirbReady': '可以转生。选择一个永久保留的本能。',
    'rebirbMaxed': '戴夫已满级。转生完成。',
    'rebirbWarning': '升满戴夫的所有升级以解锁转生。',
    'rebirbCountLabel': '转生',
    'rebirbCycleLabel': '周期金币',
    'rebirbLevelLabel': '等级',
    'rebirbInstinctsLabel': '本能',
    'rebirbBonusesLabel': '被动加成',
    'rebirbCurrentProgress': '等级 {currentLevel}',
    'rebirbTargetProgress': '达到等级 {level}',
    'rebirbScavenger': '旅行',
    'rebirbSweep': '觅食',
    'rebirbGilded': '镀金',
    'rebirbMoveBonus': '旅行',
    'rebirbSweepBonus': '觅食范围',
    'rebirbGoldBonus': '金币',
    'daveGold': '技能点',
    'daveGoldShort': '点',
    'startCharge': '开始充能',
    'milestones': {
        'firstHop': {'label': '首次跳跃', 'description': '戴夫开始或恢复一轮后更快投入工作。'},
        'quickFeet': {'label': '快脚', 'description': '戴夫在附近目标之间移动耗时更少。'},
        'sharpEyes': {'label': '锐眼', 'description': '戴夫更擅长捡起更强的爆米花群。'},
        'staysBusy': {'label': '忙碌不止', 'description': '每次觅食转生 +3 觅食范围，而非 +2。'},
        'davesSons': {'label': '戴夫的孩子们', 'description': '戴夫是个骄傲的父亲！他的两个毛茸茸的小儿子在觅食轮次中陪伴他，开心地收集爆米花。'},
        'workRhythm': {'label': '工作节奏', 'description': "在戴夫菜单上解锁自动戴夫转生功能。"},
        'fieldSense': {'label': '场地感知', 'description': '戴夫在稀疏或别扭的地形中也能更可靠地工作。'},
        'davesFamily': {'label': '戴夫的家人', 'description': '戴夫满级了！转生锁定。他的妻子加入庆祝，爆米花人人有份！'},
    },
    'autoRebirbLabel': '自动转生',
    'autoRebirbOn': '开',
    'autoRebirbOff': '关',
    'autoRebirbTurnOn': '点击开启',
    'autoRebirbTurnOff': '点击关闭',
    'autoRebirbAssignPointsFirst': '先分配点数',
    'autoRebirbTurnOnShort': '开启',
    'rebirbSpendProgress': '花费 {level} 级以转生',
    'rebirbLevelProgress': '等级 {current}/{level} 以转生',
}

# ============ seagull ============
zh['seagull'] = {
    'title': '海鸥',
    'desc': '嗨！你不在的时候我可以帮你钓鱼！',
    'active': '生效中 - 钓鱼中...',
    'inactive': '未激活',
    'start': '支付 1,000 种子（10 分钟）',
    'intro': ['嘎！你好啊！', '你看起来很喜欢钓鱼，嘎！', '我本人可是钓鱼高手。只要一点点费用……严格来说只要种子……', '你不在的时候我可以帮你钓鱼。', '需要帮忙随时叫我！'],
    'timeRemaining': '剩余时间',
    'nextCatch': '下次捕获',
    'paused': '已暂停',
    'addTime': '加时间',
    'amount': '数量',
    'cost': '成本',
    'max24h': '最多 24 小时',
    'status': '状态',
    'statusActive': '生效中',
    'forecast': '预报',
    'nextForecastIn': '下次预报：{time}',
    'route': '路线',
    'frenzy': '狂潮',
    'cooldown': '冷却',
    'autoRebirb': '自动转生',
    'autoRebirbLocked': '50 次海鸥转生后解锁。',
    'autoRebirbOnTooltip': '自动转生已开启。海鸥就绪时会自动转生。',
    'autoRebirbOffTooltip': '自动转生已关闭。点击开启。',
    'autoState': '自动：{state}',
    'rebirbReady': '可以转生。',
    'rebirbReachLevel': '达到 {level} 级以转生。',
    'bridgeFirstFleetTitle': '桥优先舰队',
    'bridgeFirstFleetBody': '均衡是安全默认，猎手追逐优质鱼，训练加速舰队成长。预报每 1 小时游戏时间轮换，偶尔出现稀有模式，传说模式非常罕见。',
    'speed': '速度',
    'rare': '稀有',
    'xp': '经验',
    'rebirbMilestones': '转生里程碑',
    'ready': '就绪',
    'lockedProgress': '锁定 {current}/{required}',
    'unlockAtRebirbs': '{count} 次转生后解锁。',
    'dailyLegendaryLockedDetail': '{count} 次转生后解锁。每日传说会掷出专家路线的传说鱼。',
    'dailyLegendaryReadyDetail': '存入的专家传说已就绪。下次触发后冷却重置为 {hours} 小时。',
    'dailyLegendaryNextDetail': '下次存入的专家传说在 {time}。',
    'noDailyLegendary': '尚未捕获每日传说。',
    'lastCatch': '上次捕获：{catch}',
    'nextProc': '下次触发：{time}',
    'readyNowCooldown': '现在已就绪。下次触发后冷却重置为 {hours} 小时。',
    'noShinyYet': '还没有闪光',
    'justNow': '刚刚',
    'routeLabels': {'bridge': '桥', 'expedition_f1': '第 1 层', 'expedition_f2': '第 2 层', 'expedition_f4': '第 4 层', 'expedition_f6': '第 6 层'},
    'routeButtonLabels': {'bridge': '桥', 'expedition_f1': 'F1', 'expedition_f2': 'F2', 'expedition_f4': 'F4', 'expedition_f6': 'F6'},
    'doctrineLabels': {'balanced': '均衡', 'hunter': '猎手', 'training': '训练'},
    'doctrineDescriptions': {'balanced': '最佳总捕获量，最安全的默认选择。', 'hunter': '捕获更少，但鱼的质量和重量更好。', 'training': '最佳舰队经验和麻雀分享，鱼的质量较弱。'},
    'doctrinePendingSuffix': '待定',
    'doctrinePendingDesc': '在当前捕获后生效。',
    'forecasts': {
        'bustling_shoal': {'label': '热闹鱼群', 'description': '均衡获得适度的捕获率提升。'},
        'predator_wake': {'label': '掠食者尾流', 'description': '猎手获得适度的稀有度和重量提升。'},
        'study_current': {'label': '研习洋流', 'description': '训练获得适度的经验和分享提升。'},
        'silver_thermals': {'label': '银色热流', 'description': '均衡捕获更快、价值略高，稀有度提升更好。'},
        'blood_tide': {'label': '血潮', 'description': '猎手获得强力稀有度提升和更重的捕获。'},
        'archive_bloom': {'label': '档案绽放', 'description': '训练获得更强经验、更好分享，稀有度惩罚更轻。'},
        'kings_tide': {'label': '王潮', 'description': '某一种风格获得巨大的速度、稀有度和价值加成。'},
    },
    'kingsTideDynamicDesc': '{doctrine} 获得巨大的速度、稀有度和价值加成。',
    'milestones': {
        'frenzy': {'label': '狂潮', 'description': '解锁舰队狂潮，一段让海鸥捕获速度翻倍的短促爆发。'},
        'reborn': {'label': '重生', 'description': '解锁重生进度，并把海鸥最高等级从 50 提升到 100。'},
        'dailyLegendary': {'label': '每日传说', 'description': '专家为当前路线存入一条必出的传说捕获，进入冷却。自动转生解锁。'},
        'secondGull': {'label': '第 2 只海鸥', 'description': '解锁第二个海鸥槽位。'},
        'echo': {'label': '回声', 'description': '每次捕获有 8% 几率翻倍'},
        'moonlit': {'label': '月光', 'description': '自上次闪光捕获起，每小时闪光几率 +0.4x'},
        'sparrowShare': {'label': '麻雀分享', 'description': '海鸥经验也提供麻雀经验。'},
        'specialist': {'label': '专家', 'description': '解锁一只只捕获稀有+鱼的专家海鸥'},
        'alpha': {'label': '领袖', 'description': '所有转生加成（速度、稀有几率、经验）翻倍'},
    },
}

# ============ sunflowerUpgrades ============
zh['sunflowerUpgrades'] = {
    'd_mine_combat_regen_penalty': {'name': '战斗回复减免', 'description': '战斗中鹦鹉生命回复惩罚降低 10%。'},
    'd_mine_crow_contract': {'name': '乌鸦合同', 'description': '解锁乌鸦挖矿经验，并 +10% 永久矿洞矿石价值。'},
    'd_mine_anvil_perch': {'name': '铁砧栖架', 'description': '解锁护甲的金属抽取，并 +12% 永久矿洞矿石价值。'},
    'd_mine_core_mark': {'name': '核心标记', 'description': '乌鸦标记珍贵矿石。被标记的矿石会裂开，并基于其最大耐久承受一次重击。+15% 永久矿洞矿石价值。'},
    'd_mine_bellowed_refinery': {'name': '鼓风精炼厂', 'description': '改善原矿精炼、金属抽取效率，并 +18% 永久矿洞矿石价值。'},
    'd_mine_load_bearing_rivets': {'name': '承重铆钉', 'description': '为鹦鹉回复解锁铆钉抽取目标，并 +20% 永久矿洞矿石价值。'},
    'd_mine_core_set_armor': {'name': '核心护甲', 'description': '为鹦鹉伤害、矿洞伤害解锁核心抽取目标，并 +25% 永久矿洞矿石价值。'},
    'd_mine_royal_core_cache': {'name': '皇家核心储备', 'description': '可重复。每级 +5% 永久矿洞矿石价值。'},
    'd_sunflower_machine': {'name': '向日葵贩卖机', 'description': '解锁向日葵平台'},
    'd_unlock_desert_tree': {'name': '解锁沙漠之树', 'description': '用传说钥匙解锁一条新分支'},
    'd_desert_core_mockup': {'name': '沙漠核心', 'description': '沙漠爆米花有 5% 几率生成金色爆米花'},
    'd_desert_quest_merchant': {'name': '任务商人', 'description': '解锁任务商人。'},
    'd_desert_fever': {'name': '沙漠狂热', 'description': '沙漠爆米花价值提升 5 倍。'},
    'd_desert_expedition_points': {'name': '沙漠远征', 'description': '探险中鹦鹉技能点 +100%。'},
    'd_desert_golden_popcorn_chance_2': {'name': '日晒谷粒', 'description': '+2.5% 沙漠金色爆米花几率。'},
    'd_desert_golden_popcorn_chance_3': {'name': '海市蜃楼谷粒', 'description': '+2.5% 沙漠金色爆米花几率。'},
    'd_desert_golden_popcorn_gain_2': {'name': '淘金热', 'description': '获得的金色爆米花 x1.5。'},
    'd_desert_popcorn_spawn_rate': {'name': '沙丘绽放', 'description': '种子提升获得的金色爆米花。'},
    'd_desert_bloom_netting': {'name': '花网', 'description': '+15% 沙漠爆米花生成速率。'},
    'd_desert_blossom_route': {'name': '花途', 'description': '探险掉落 +5% 灵魂光环几率。'},
    'd_desert_bloom_reservoir': {'name': '花池', 'description': '获得的金色爆米花 x1.35。'},
    'd_desert_dune_scouts': {'name': '沙丘侦察兵', 'description': '+50% 探险掉落价值。'},
    'd_desert_golden_popcorn_chance_4': {'name': '鎏金微光', 'description': '+2.5% 沙漠金色爆米花几率。'},
    'd_desert_dave_golden_xp': {'name': '镀金课程', 'description': '戴夫收集金色爆米花时获得 2 倍经验。'},
    'd_desert_dave_popcorn_xp': {'name': '稳健啄食', 'description': '戴夫收集普通爆米花时获得 2 倍经验。'},
    'd_desert_seed_generation_x5': {'name': '沙丘肥料', 'description': '向日葵种子生成翻倍。'},
    'd_desert_auto_potion': {'name': '应急药瓶', 'description': '生命值低于设定阈值时自动使用探险药水。'},
    'd_desert_shiny_enemies': {'name': '鎏金敌手', 'description': '探险敌人有 1% 几率生成闪光。'},
    'd_seed_feeder': {'name': '种子喂食器', 'description': '用选定比例的种子收入自动喂食麻雀'},
    'd_seed_multiplier': {'name': '种子肥料', 'description': '羽毛提升种子'},
    'd_rebirth_playtime': {'name': '时间就是金钱', 'description': '羽毛 x 游玩时长'},
    'd_golden_harvest': {'name': '金色丰收', 'description': '种子与羽毛 x3'},
    'd_unlock_evolve': {'name': '解锁进化', 'description': '新的进化在等待'},
    'd_seed_synergy': {'name': '种子协同', 'description': '种子提升爆米花'},
    'd_butter_bonanza': {'name': '黄油盛宴', 'description': '+50% 黄油爆米花'},
    'd_sparrow_snacks': {'name': '美味零食', 'description': '+50% 麻雀经验'},
    'd_rainbow_aura': {'name': '彩虹光环', 'description': '彩虹爆米花 x2'},
    'd_cheese_powder': {'name': '奶酪工厂', 'description': '+50% 奶酪爆米花'},
    'd_fishing_luck': {'name': '垂钓者的祝福', 'description': '+25% 钓鱼幸运'},
    'd_fast_reeling': {'name': '快速收线', 'description': '-25% 收线时间'},
    'd_seagull_synergy': {'name': '海鸥协同', 'description': '鱼经验增益影响海鸥'},
    'd_popcorn_cap': {'name': '爆米花粮仓', 'description': '爆米花上限 x2'},
    'd_swift_wings': {'name': '迅捷之翼', 'description': '鸟速 x1.3'},
    'd_auto_gen': {'name': '自动生成器', 'description': '自动生成种子'},
    'd_faster_seeds': {'name': '高效耕作', 'description': '种子速度 x2'},
    'd_pickup_range': {'name': '真空', 'description': '拾取范围 x1.25'},
    'd_seed_multiplier_unlocker': {'name': '种子精通', 'description': '解锁种子升级'},
    'd_seed_pipeline': {'name': '种子管道', 'description': '+25% 种子速度'},
    'd_pop_max_lvl': {'name': '界限突破', 'description': '+2 爆米花倍率最大等级'},
    'd_auto_fishing': {'name': '自动钓鱼', 'description': '自动化钓鱼'},
    'd_seagull_xp': {'name': '海鸥训练', 'description': '+50% 海鸥经验'},
    'd_fish_seeds': {'name': '鱼种', 'description': '历史捕获总鱼数提升种子'},
    'd_seed_market': {'name': '莫奈塔商店', 'description': '莫奈塔提升鱼价值'},
    'd_trophy_bonus': {'name': '战利品加成', 'description': '爆米花 x 最重鱼'},
    'd_golden_rain': {'name': '金色瀑布', 'description': '每秒获得至多 0.025% 转生羽毛（递减）'},
    'd_prism_shine': {'name': '棱镜闪光', 'description': '+25% 爆米花价值'},
    'd_platinum_wings': {'name': '白金之翼', 'description': '+15% 移动速度'},
    'd_deep_dive': {'name': '深潜', 'description': '+20% 稀有鱼几率'},
    'd_fish_frenzy': {'name': '鱼狂潮', 'description': '-20% 钓鱼冷却'},
    'd_sparrow_legacy': {'name': '麻雀传承', 'description': '进化保留 25% 麻雀经验'},
    'd_sparrow_xp_2': {'name': '鸟脑', 'description': '+25% 麻雀经验'},
    'd_free_seeds': {'name': '自然补贴', 'description': '升级不消耗种子'},
    'd_unlock_rod_ancient': {'name': '远古丛林', 'description': '解锁远古丛林'},
    'd_unlock_rod_divine': {'name': '神圣', 'description': '解锁神圣'},
    'd_unlock_rod_celestial': {'name': '香蕉', 'description': '解锁香蕉'},
    'd_sparrow_drain_power': {'name': '麻雀共鸣', 'description': '解锁共鸣。'},
    'd_sparrow_mitosis': {'name': '麻雀有丝分裂', 'description': '解锁有丝分裂。'},
    'd_double_catch': {'name': '双倍捕获', 'description': '10% 几率钓到 2 条鱼'},
    'd_double_fish_buff': {'name': '额外胃口', 'description': '新增一个生效鱼增益槽位'},
    'd_treasure_map': {'name': '藏宝图', 'description': '+50% 宝藏几率'},
    'd_treasure_appraisal': {'name': '宝藏鉴定', 'description': '宝藏提供 2 倍莫奈塔'},
    'd_fish_value': {'name': '市场繁荣', 'description': '鱼售价 x2'},
    'd_rod_chance': {'name': '精准抛竿', 'description': '+15% 鱼竿鱼几率'},
    'd_critical_reel': {'name': '暴击抛竿', 'description': '10% 几率立即捕获'},
    'd_xp_tome': {'name': '垂钓专家', 'description': '+50% 钓鱼经验'},
    'd_bulk_bonus': {'name': '批发', 'description': '卖出超过 10 条时 +20% 价值'},
    'd_profit_surge': {'name': '黄金出售', 'description': '1% 几率 10 倍价值'},
    'd_treasure_seeker': {'name': '宝藏猎人', 'description': '宝藏几率 x2'},
    'd_shiny_scale': {'name': '棱彩徽章', 'description': '幸运随最高鱼竿等级提升'},
    'd_junk_repurpose': {'name': '堆肥', 'description': '垃圾可卖成莫奈塔'},
    'd_seed_bag': {'name': '肥沃土壤', 'description': '+50% 全局种子生成'},
    'd_sparrow_hoard': {'name': '信鸽', 'description': '麻雀收集价值 x2'},
    'd_wing_mastery_plus': {'name': '翅膀精通', 'description': '+10 翅膀训练等级'},
    'd_silo_mastery_plus': {'name': '粮仓精通', 'description': '+10 爆米花上限等级'},
    'd_butter_hose': {'name': '黄油软管', 'description': '爆米花价值 x1.5'},
    'd_focus_training': {'name': '专注训练', 'description': '拾取半径 x1.3'},
    'd_quantum_corn': {'name': '量子玉米', 'description': '生成速率 x1.2'},
    'd_kernel_polish': {'name': '谷粒抛光', 'description': '爆米花价值 x2'},
    'd_sparrow_wisdom': {'name': '麻雀智慧', 'description': '+50% 麻雀经验'},
    'd_sparrow_lineage': {'name': '祖传谱系', 'description': '传承现在保留 50% 麻雀经验'},
    'd_twig_popcorn_boost': {'name': '树枝协同', 'description': '树枝乘以爆米花'},
    'd_unlock_more_twigs': {'name': '树枝精通', 'description': '解锁树枝升级'},
    'd_forest_bounty': {'name': '森林恩赐', 'description': '树枝 x3 且木材 x2'},
    'd_woodland_resonance': {'name': '林地共鸣', 'description': '木材提升树枝'},
    'd_forest_tree_damage': {'name': '磨利利爪', 'description': '+1 树木伤害'},
    'd_forest_chain_chop_plus': {'name': '连锁砍伐加强', 'description': '连锁砍伐多砍一棵树'},
    'd_forest_max_trees': {'name': '森林扩建', 'description': '+15 最大树木等级'},
    'd_sparrow_rebirb_preserve': {'name': '转生保留', 'description': '保留 50% 麻雀转生倍率'},
    'd_golden_twig': {'name': '金色树枝', 'description': '5% 几率 x100 树枝'},
    'd_golden_twig_2': {'name': '荣耀树枝', 'description': '金色树枝倍率 x2'},
    'd_feathered_help': {'name': '羽翼相助', 'description': '麻雀提升树枝价值（每只麻雀 +1 基础树枝）'},
    'd_feathered_synergy': {'name': '麻雀协作', 'description': '羽翼相助效果翻倍'},
    'd_aurelian_resonance': {'name': '鎏金共鸣', 'description': '金色树枝倍率和连锁几率'},
    'd_flock_synchrony': {'name': '鸟群同步', 'description': '全局树枝倍率随麻雀缩放'},
    'd_abyssal_light': {'name': '深渊之光', 'description': '+50% 平均鱼重'},
    'd_net_mastery': {'name': '渔网精通', 'description': '自动钓鱼 10% 几率 x2 鱼'},
    'd_amber_alchemy': {'name': '琥珀洋流', 'description': '钓鱼后 5% 几率获得种子加成'},
    'd_leviathan_mastery': {'name': '利维坦精通', 'description': '鱼价值随重量平方缩放'},
    'd_ocean_bounty': {'name': '海洋恩赐', 'description': '钓鱼获得种子'},
    'd_gravity_field': {'name': '引力场', 'description': '被动爆米花牵引（弱）'},
    'd_golden_butter': {'name': '金色黄油', 'description': '爆米花价值随金色羽毛缩放'},
    'd_crit_pop': {'name': '暴击爆米花', 'description': '1% 几率红色爆米花（100 倍）'},
    'd_void_silo': {'name': '虚空粮仓', 'description': '+10% 总爆米花容量'},
    'd_hyper_metabolism': {'name': '超速代谢', 'description': '爆米花提供可叠加的速度增益'},
    'd_hive_mind': {'name': '神经超频', 'description': '麻雀速度上限提升 50%'},
    'd_phoenix_down': {'name': '凤凰之羽', 'description': '进化时麻雀保留经验'},
    'd_seed_bank': {'name': '种子银行', 'description': '每分钟 +1% 种子利息（5T 种子软上限）'},
    'd_mecha_birb': {'name': '机械鸟', 'description': '麻雀收集爆米花 x2'},
    'd_ancestral_radio': {'name': '祖传电台', 'description': '海鸥 -> 麻雀经验分享 10%'},
    'd_lunar_compass': {'name': '月相罗盘', 'description': '海鸥捕获重量 +35%'},
    'd_legend_beacon': {'name': '传说信标', 'description': '每日传说冷却 24h->16h，每日闪光 1%->3%'},
    'd_migration_amplifier': {'name': '海鸥转生放大器', 'description': '每级 +5%，仅影响海鸥转生的稀有和经验效果'},
    'd_gull_sonar': {'name': '海鸥声呐', 'description': '海鸥掷两次并保留更稀有的捕获'},
    'd_rare_routes': {'name': '稀有路线', 'description': '海鸥捕获 +15% 稀有重掷几率'},
    'd_echo_vectors': {'name': '回声矢量', 'description': '+10% 复制捕获几率'},
    'd_fleet_training': {'name': '舰队训练', 'description': '每级 +6% 海鸥经验'},
    'd_frenzy_reactor': {'name': '狂潮反应堆', 'description': '狂潮持续时间 x1.5'},
    'd_cold_start': {'name': '冷启动', 'description': '狂潮冷却 x0.65'},
    'd_patrol_network': {'name': '巡逻网络', 'description': '每级 +1% 复制捕获几率（上限 5%）'},
    'd_mine_fish_radius_parrot': {'name': '鱼半径联动', 'description': '鱼的半径增益影响鹦鹉半径'},
    'd_desert_golden_popcorn_chance': {'name': '镀金谷粒', 'description': '+2.5% 沙漠金色爆米花几率。'},
    'd_desert_seed_generation_x2': {'name': '向日葵灌溉', 'description': '向日葵种子生成翻倍。'},
    'd_desert_rebirb_golden_feathers': {'name': '转生操纵', 'description': '转生获得的金色羽毛 +100%。'},
    'd_desert_rebirb_parrot_vitality': {'name': '生机羽毛', 'description': '探险中鹦鹉生命 +25%。'},
    'd_desert_field_notes': {'name': '野外笔记', 'description': '探险中每秒获得 1 点鹦鹉技能点。'},
    'd_desert_scout_gull': {'name': '侦察海鸥', 'description': '派海鸥前往探险钓鱼层。'},
    'd_desert_tackle_crate': {'name': '钓具箱', 'description': '派遣的海鸥钓鱼快 35% 并重掷弱捕获。'},
    'd_desert_guarded_plumage': {'name': '守护羽毛', 'description': '+15% 探险鹦鹉生命。'},
    'd_desert_salvage_rights': {'name': '打捞权', 'description': '+25% 探险掉落价值。'},
    'd_desert_signal_smoke': {'name': '信号烟', 'description': '获得的金色爆米花 x1.5。'},
    'd_desert_auric_bargain': {'name': '鎏金交易', 'description': '金色爆米花升级价格降低 25%。'},
    'd_desert_collared_dove': {'name': '环颈斑鸠', 'description': '解锁一只以集群俯冲扫食爆米花的沙漠鸟。'},
    'd_desert_golden_popcorn_mult_unlock': {'name': '镀金催化剂', 'description': '在转生商店解锁金色爆米花倍率。'},
    'd_desert_seed_generation_x2_plus': {'name': '沙丘肥力', 'description': '向日葵种子生成翻倍。'},
    'd_desert_auric_blueprints': {'name': '鎏金蓝图', 'description': '在爆米花商店解锁金色粮仓。'},
    'd_desert_oasis_recovery': {'name': '绿洲恢复', 'description': '每级 +10% 生命回复价值。'},
    'd_desert_popcorn_gain_x2': {'name': '沙暴丰收', 'description': '获得的爆米花翻倍。'},
    'd_desert_warpath': {'name': '沙丘战途', 'description': '每级 +10% 探险伤害。'},
    'd_desert_field_notes_plus': {'name': '镀金利润', 'description': '每级 +33.3% 获得的金色爆米花。'},
    'd_desert_muad_birb': {'name': '穆阿德鸟', 'description': '金色爆米花提升探险技能点。'},
    'd_desert_sandstorm': {'name': '沙尘暴', 'description': '沙漠可能发生沙尘暴，把所有爆米花变成金色'},
    'd_desert_golden_popcorn_x2': {'name': '珍稀丰收', 'description': '沙漠中获得的金色爆米花翻倍。'},
    'd_spirit_scouting': {'name': '灵魂侦察', 'description': '每级 +10% 鹦鹉伤害'},
    'd_spirit_shell': {'name': '灵魂外壳', 'description': '每级 +10% 鹦鹉最大生命'},
    'd_spirit_momentum': {'name': '灵魂动能', 'description': '每级 +2% 鹦鹉攻速/移速'},
}

# 合并程序化翻译的 fish 分类
zh['fish'] = json.load(open('fish_zh.json', encoding='utf-8'))

# 合并剩余分类（misc / mapEditor / profiler / multiplayer）
_rest = json.load(open('rest_part1.json', encoding='utf-8'))
for _k, _v in _rest.items():
    zh[_k] = _v

out = io.open('zh_dict.json', 'w', encoding='utf-8')
json.dump(zh, out, ensure_ascii=False, indent=1)
out.close()
print('batch 1 done, categories:', list(zh.keys()))
